// Shared workspace utilities for unreal-index.
// Used by cli.js, setup-gui.js, and mcp-bridge.js.
// Zero dependencies — Node.js built-ins only.

import { readFileSync, existsSync } from 'fs';
import { join } from 'path';

// ── Path utilities ──────────────────────────────────────────

export function fwd(path) {
  return path.replace(/\\/g, '/');
}

export function getWslRoot(rootDir) {
  return fwd(rootDir).replace(/^([A-Za-z]):/, (_, d) => `/mnt/${d.toLowerCase()}`);
}

// ── Workspaces config I/O ───────────────────────────────────

export function loadWorkspacesConfig(rootDir) {
  const wsPath = join(rootDir, 'workspaces.json');
  if (!existsSync(wsPath)) return null;
  // Let JSON parse errors propagate so callers can distinguish
  // "file missing" (null) from "file has syntax errors" (thrown error).
  return JSON.parse(readFileSync(wsPath, 'utf-8'));
}

export function ensureWorkspacesDefaults(wsConfig) {
  if (!wsConfig.workspaces) wsConfig.workspaces = {};
  if (!wsConfig.defaultWorkspace) {
    const names = Object.keys(wsConfig.workspaces);
    wsConfig.defaultWorkspace = names[0] || 'main';
  }
  if (!wsConfig.dockerImage) wsConfig.dockerImage = 'unreal-index:latest';
  if (!wsConfig.shared) {
    wsConfig.shared = {
      exclude: ['**/Intermediate/**', '**/Saved/**', '**/DerivedDataCache/**', '**/Binaries/**'],
      zoekt: { parallelism: 4, reindexDebounceMs: 5000 },
      watcher: { debounceMs: 100, reconcileIntervalMinutes: 10 },
    };
  }
  return wsConfig;
}

// ── Per-workspace config I/O ────────────────────────────────

export function loadWorkspaceConfig(rootDir, workspaceName) {
  const configPath = join(rootDir, 'workspace-configs', `${workspaceName}.json`);
  if (!existsSync(configPath)) return null;
  try {
    return JSON.parse(readFileSync(configPath, 'utf-8'));
  } catch {
    return null;
  }
}

// ── Docker compose generation ───────────────────────────────

export function getWorkspaceMemoryLimitGB(wsConfig, workspaceName, rootDir) {
  const ws = wsConfig.workspaces[workspaceName];
  // User-configurable override takes priority
  if (ws && ws.memoryLimitGB && ws.memoryLimitGB > 0) {
    return ws.memoryLimitGB;
  }
  // Auto-calculate based on project languages.
  // Memory is dominated by in-memory index size which varies heavily by language:
  //   content (assets): ~1.5GB for a large game (200K+ assets)
  //   cpp (engine):     ~2GB for full UE engine source
  //   cpp (game):       ~0.5GB for typical game source+plugins
  //   angelscript:      ~0.5GB for typical script project
  //   config:           negligible
  // Base overhead: ~2GB (Node.js heap, SQLite, Zoekt webserver, OS)
  const config = loadWorkspaceConfig(rootDir, workspaceName);
  const projects = config?.projects || [];
  let estimatedGB = 2; // base overhead
  for (const p of projects) {
    const isEngine = /engine/i.test(p.name);
    switch (p.language) {
      case 'content':    estimatedGB += 1.5; break;
      case 'cpp':        estimatedGB += isEngine ? 2 : 0.5; break;
      case 'angelscript': estimatedGB += 0.5; break;
      default:           estimatedGB += 0.1; break;
    }
  }
  // Round up to nearest 0.5, clamp to [4, 16]
  return Math.min(16, Math.max(4, Math.ceil(estimatedGB * 2) / 2));
}

/**
 * Generate docker-compose.yml content as a string. Does NOT write to disk.
 */
export function generateDockerComposeContent(wsConfig, rootDir) {
  const lines = [
    "# Generated by unreal-index. Re-run 'npm start' or 'npm run setup' to regenerate.",
    'services:',
  ];

  for (const [name, ws] of Object.entries(wsConfig.workspaces)) {
    const memGB = getWorkspaceMemoryLimitGB(wsConfig, name, rootDir);
    const swapGB = memGB + 2;
    const vol = ws.volumePrefix || name; // preserved across renames
    lines.push(`  ${name}:`);
    lines.push(`    build:`);
    lines.push(`      context: .`);
    lines.push(`      args:`);
    lines.push(`        BUILD_GIT_HASH: \${BUILD_GIT_HASH:-unknown}`);
    lines.push(`    image: ${wsConfig.dockerImage}`);
    lines.push(`    container_name: unreal-index-${name}`);
    lines.push(`    ports:`);
    lines.push(`      - "${ws.port}:3847"`);
    lines.push(`    volumes:`);
    lines.push(`      - ${vol}-db:/data/db`);
    lines.push(`      - ${vol}-mirror:/data/mirror`);
    lines.push(`      - ${vol}-zoekt:/data/zoekt-index`);
    lines.push(`      - ./workspaces.json:/app/workspaces.json:ro`);
    lines.push(`      - ./workspace-configs/${name}.json:/app/config.json:ro`);
    lines.push(`    mem_limit: ${memGB}g`);
    lines.push(`    memswap_limit: ${swapGB}g`);
    lines.push(`    restart: unless-stopped`);
    lines.push(`    stop_grace_period: 15s`);
    lines.push('');
  }

  lines.push('volumes:');
  for (const [name, ws] of Object.entries(wsConfig.workspaces)) {
    const vol = ws.volumePrefix || name;
    lines.push(`  ${vol}-db:`);
    lines.push(`    name: unreal-index-${vol}-db`);
    lines.push(`  ${vol}-mirror:`);
    lines.push(`    name: unreal-index-${vol}-mirror`);
    lines.push(`  ${vol}-zoekt:`);
    lines.push(`    name: unreal-index-${vol}-zoekt`);
  }

  return lines.join('\n') + '\n';
}

// ── Compose validation ──────────────────────────────────────

/**
 * Parse a docker-compose.yml string to extract service definitions.
 * Returns Map<serviceName, { port, volumes, memLimit, containerName }>.
 * Simple line-based parser — no YAML library needed for our generated format.
 */
function parseComposeServices(content) {
  const services = new Map();
  const lines = content.split('\n');
  let currentService = null;
  let inServices = false;
  let inVolumes = false;

  for (const line of lines) {
    const trimmed = line.trimEnd();

    if (trimmed === 'services:') { inServices = true; inVolumes = false; continue; }
    if (trimmed === 'volumes:') { inServices = false; inVolumes = true; continue; }

    if (inServices) {
      // Top-level service name (2-space indent, ends with :)
      const serviceMatch = trimmed.match(/^ {2}(\w[\w-]*):$/);
      if (serviceMatch) {
        currentService = serviceMatch[1];
        services.set(currentService, { ports: [], volumes: [], memLimit: null, containerName: null });
        continue;
      }

      if (currentService && services.has(currentService)) {
        const svc = services.get(currentService);
        const portMatch = trimmed.match(/- "(\d+):(\d+)"/);
        if (portMatch) svc.ports.push(`${portMatch[1]}:${portMatch[2]}`);

        const memMatch = trimmed.match(/mem_limit:\s*(\S+)/);
        if (memMatch) svc.memLimit = memMatch[1];

        const containerMatch = trimmed.match(/container_name:\s*(\S+)/);
        if (containerMatch) svc.containerName = containerMatch[1];

        const volMatch = trimmed.match(/- (.+:\/\S+)/);
        if (volMatch) svc.volumes.push(volMatch[1]);
      }
    }
  }

  return services;
}

/**
 * Compare on-disk docker-compose.yml with expected content from workspaces.json.
 * Returns { inSync, diffs[], expected }.
 */
export function validateComposeSync(rootDir, wsConfig) {
  const expected = generateDockerComposeContent(wsConfig, rootDir);
  const composePath = join(rootDir, 'docker-compose.yml');

  if (!existsSync(composePath)) {
    return { inSync: false, diffs: ['docker-compose.yml does not exist'], expected };
  }

  const actual = readFileSync(composePath, 'utf-8');

  // Quick check — exact match
  if (actual === expected) {
    return { inSync: true, diffs: [], expected };
  }

  // Structural comparison for better diff messages
  const actualServices = parseComposeServices(actual);
  const expectedServices = parseComposeServices(expected);
  const diffs = [];

  // Services in expected but missing from actual
  for (const name of expectedServices.keys()) {
    if (!actualServices.has(name)) {
      diffs.push(`service '${name}' missing from docker-compose.yml`);
    }
  }

  // Services in actual but not expected
  for (const name of actualServices.keys()) {
    if (!expectedServices.has(name)) {
      diffs.push(`service '${name}' in docker-compose.yml but not in workspaces.json`);
    }
  }

  // Compare shared services
  for (const [name, exp] of expectedServices) {
    const act = actualServices.get(name);
    if (!act) continue;

    if (JSON.stringify(act.ports) !== JSON.stringify(exp.ports)) {
      diffs.push(`port for '${name}' differs: actual ${act.ports.join(',')} vs expected ${exp.ports.join(',')}`);
    }
    if (act.memLimit !== exp.memLimit) {
      diffs.push(`memory limit for '${name}' differs: actual ${act.memLimit} vs expected ${exp.memLimit}`);
    }
    if (act.containerName !== exp.containerName) {
      diffs.push(`container name for '${name}' differs: actual ${act.containerName} vs expected ${exp.containerName}`);
    }
  }

  // If structural comparison found nothing but content differs (whitespace, comments, etc.)
  if (diffs.length === 0) {
    diffs.push('minor formatting differences detected');
  }

  return { inSync: false, diffs, expected };
}
